/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.35
 * Generated at: 2016-05-30 09:09:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>Peter Piper's Pickled Peppers</title>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"stylesheets/home.css\">\n");
      out.write("        <link rel=\"shortcut icon\" href=\"images/favicon.ico\" type=\"image/x-icon\">\n");
      out.write("        <link rel=\"icon\" href=\"images/favicon.ico\" type=\"image/x-icon\">\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <h1>Peter sells peppers</h1>\n");
      out.write("        <div class=\"subtitle-div\">\n");
      out.write("            Suppliers of the universe's best peppers money can buy.\n");
      out.write("        </div>\n");
      out.write("        <a href='management/management.html'>\n");
      out.write("            <div class='center-div' id='management'>\n");
      out.write("                Management Team\n");
      out.write("            </div>\n");
      out.write("        </a>\n");
      out.write("        <div class='order'>\n");
      out.write("\t\t<hr>\n");
      out.write("            <form method='post' id='order-form' onsubmit='return processForm();'>\n");
      out.write("                <table class='ship-form'>\n");
      out.write("                    <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>First Name:</td>\n");
      out.write("                            <td><input type=\"text\" class=\"in_txt\" id=\"first-name\" onkeyup=\"checkFirstNameWhileTyping()\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/red_x.gif\" alt=\"Error!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"first-name-good\"></img>\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/green_check.png\" alt=\"Success!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"first-name-bad\"></img>\n");
      out.write("                        </td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>Last Name:</td>\n");
      out.write("                            <td><input type=\"text\" class=\"in_txt\" id=\"last-name\" onkeyup=\"checkLastNameWhileTyping()\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/red_x.gif\" alt=\"Error!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"last-name-good\"></img>\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/green_check.png\" alt=\"Success!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"last-name-bad\"></img>\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>Credit Card:</td>\n");
      out.write("                            <td><input type=\"text\" class=\"in_txt\" id=\"credit-card\" onkeyup=\"checkCreditCardWhileTyping()\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/red_x.gif\" alt=\"Error!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"credit-card-good\"></img>\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/green_check.png\" alt=\"Success!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"credit-card-bad\"></img>\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>Street Address:</td>\n");
      out.write("                            <td><input type=\"text\" class=\"in_txt\" id=\"address\" onkeyup=\"checkAddressWhileTyping()\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/red_x.gif\" alt=\"Error!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"address-good\"></img>\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/green_check.png\" alt=\"Success!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"address-bad\"></img>\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("                        </tr>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("                            <td>Phone Number:</td>\n");
      out.write("                            <td><input type=\"text\" class=\"in_txt\" id=\"phone\" onkeyup=\"checkPhoneWhileTyping()\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/red_x.gif\" alt=\"Error!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"phone-good\"></img>\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/green_check.png\" alt=\"Success!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"phone-bad\"></img>\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>Zip code:</td>\n");
      out.write("                            <td><input type=\"text\" class=\"in_txt\" id=\"zip-code\" onkeyup=\"checkZipCodeWhileTyping()\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/red_x.gif\" alt=\"Error!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"zip-code-good\"></img>\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/green_check.png\" alt=\"Success!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"zip-code-bad\"></img>\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>State:</td>\n");
      out.write("                            <td><input type=\"text\" class=\"in_txt\" id=\"state\" onkeyup=\"checkStateWhileTyping()\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/red_x.gif\" alt=\"Error!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"state-good\"></img>\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/green_check.png\" alt=\"Success!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"state-bad\"></img>\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr> \n");
      out.write("                            <td>Quantity:</td>\n");
      out.write("                            <td><input type=\"text\" class=\"in_txt\" id=\"quantity\" onkeyup=\"checkQuantityWhileTyping()\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/red_x.gif\" alt=\"Error!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"quantity-good\"></img>\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/green_check.png\" alt=\"Success!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"quantity-bad\"></img>\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>Shipping speed:</td>\n");
      out.write("                            <td>\n");
      out.write("                                <input type=\"radio\" name=\"ship\" value=\"one-day\"> Burn my mouth tomorrow<br>\n");
      out.write("                                <input type=\"radio\" name=\"ship\" value=\"two-day\"> Burn my mouth two days from now<br>\n");
      out.write("                                <input type=\"radio\" name=\"ship\" value=\"other\" checked=\"checked\"> Burn my mouth whenever it gets here\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("                <br>\n");
      out.write("                <div id='submit-btn-div'>\n");
      out.write("                    <input type='submit' value='Purchase' id='submit-btn'>\n");
      out.write("\t\t\t\t<hr>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
