/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.35
 * Generated at: 2016-05-31 04:23:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Models.ShoppingCart;
import Models.ShoppingCartItem;
import java.util.ArrayList;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("Models.ShoppingCartItem");
    _jspx_imports_classes.add("Models.ShoppingCart");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>Peter Piper's Pickled Peppers</title>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"stylesheets/home.css\">\n");
      out.write("        <link rel=\"shortcut icon\" href=\"images/favicon.ico\" type=\"image/x-icon\">\n");
      out.write("        <link rel=\"icon\" href=\"images/favicon.ico\" type=\"image/x-icon\">\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <a href=\"/\" style=\"text-decoration: none;\">\n");
      out.write("            <h1>Peter sells peppers</h1>\n");
      out.write("        <a/>\n");
      out.write("        <div class=\"subtitle-div\">\n");
      out.write("            Suppliers of the universe's best peppers money can buy.\n");
      out.write("        </div>\n");
      out.write("        <a href='management/management.html'>\n");
      out.write("            <div class='center-div' id='management'>\n");
      out.write("                Management Team\n");
      out.write("            </div>\n");
      out.write("        </a>\n");
      out.write("        <hr>\n");
      out.write("        <div class=\"order-summary\">\n");
      out.write("            ");

                ShoppingCart shoppingCart = (ShoppingCart) request.getAttribute("shoppingCart");
                if(shoppingCart != null) {

            
      out.write("\n");
      out.write("            <table>\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>\n");
      out.write("                            Pepper Name\n");
      out.write("                        </th>\n");
      out.write("                        <th>\n");
      out.write("                            Description\n");
      out.write("                        </th>\n");
      out.write("                        <th>\n");
      out.write("                            Price\n");
      out.write("                        </th>\n");
      out.write("                        <th>\n");
      out.write("                            Quantity\n");
      out.write("                        </th>\n");
      out.write("                        <th>\n");
      out.write("                            Subtotal\n");
      out.write("                        </th>\n");
      out.write("                        <th>\n");
      out.write("\n");
      out.write("                        </th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                    ");

                        ArrayList<ShoppingCartItem> shoppingCartItems = shoppingCart.ShoppingCartItems;
                        for(ShoppingCartItem item : shoppingCartItems) {
                    
      out.write("\n");
      out.write("                    <tr style=\"text-align:left;\">\n");
      out.write("                        <td>\n");
      out.write("                            ");
      out.print( item.Pepper.PepperName );
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            ");
      out.print( item.Pepper.Description );
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            $");
      out.print( String.format("%.2f", item.Pepper.Price) );
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <input type=\"number\" value=\"");
      out.print( item.Quantity );
      out.write("\" id=\"quantity\" style=\"width:60px;\" onchange=\"updateQuantity(this, ");
      out.print( item.Pepper.ID);
      out.write(")\"/>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            $<span id=\"subtotal_");
      out.print( item.Pepper.ID);
      out.write('"');
      out.write('>');
      out.print( String.format("%.2f",item.Pepper.Price * item.Quantity) );
      out.write("</span>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            <a href=\"#\" style=\"color:red;\" onclick=\"removeItem(this, ");
      out.print( item.Pepper.ID);
      out.write(")\">Remove</a>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                    ");

                        }
                    
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                        Total:\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("                            $<span id=\"total\">");
      out.print( String.format("%.2f", shoppingCart.getTotal()) );
      out.write(" </span>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("            ");

                } else {
            
      out.write("\n");
      out.write("            <div>\n");
      out.write("                You have no items in your shopping cart!\n");
      out.write("            </div>\n");
      out.write("            ");

                }
            
      out.write("\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <div class='order'>\n");
      out.write("\t\t<hr>\n");
      out.write("            <form method='post' id='order-form' onsubmit='return processForm();'>\n");
      out.write("                <table class='ship-form'>\n");
      out.write("                    <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>First Name:</td>\n");
      out.write("                            <td><input type=\"text\" class=\"in_txt\" id=\"first-name\" name=\"first_name\" onkeyup=\"checkFirstNameWhileTyping()\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/red_x.gif\" alt=\"Error!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"first-name-good\"></img>\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/green_check.png\" alt=\"Success!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"first-name-bad\"></img>\n");
      out.write("                        </td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>Last Name:</td>\n");
      out.write("                            <td><input type=\"text\" class=\"in_txt\" id=\"last-name\" name=\"last_name\" onkeyup=\"checkLastNameWhileTyping()\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/red_x.gif\" alt=\"Error!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"last-name-good\"></img>\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/green_check.png\" alt=\"Success!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"last-name-bad\"></img>\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>Credit Card:</td>\n");
      out.write("                            <td><input type=\"text\" class=\"in_txt\" id=\"credit-card\" name=\"credit_card\" onkeyup=\"checkCreditCardWhileTyping()\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/red_x.gif\" alt=\"Error!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"credit-card-good\"></img>\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/green_check.png\" alt=\"Success!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"credit-card-bad\"></img>\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>Street Address:</td>\n");
      out.write("                            <td><input type=\"text\" class=\"in_txt\" id=\"address\" name=\"address\" onkeyup=\"checkAddressWhileTyping()\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/red_x.gif\" alt=\"Error!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"address-good\"></img>\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/green_check.png\" alt=\"Success!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"address-bad\"></img>\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("                        </tr>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("                            <td>Phone Number:</td>\n");
      out.write("                            <td><input type=\"text\" class=\"in_txt\" id=\"phone\" name=\"phone\" onkeyup=\"checkPhoneWhileTyping()\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/red_x.gif\" alt=\"Error!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"phone-good\"></img>\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/green_check.png\" alt=\"Success!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"phone-bad\"></img>\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>Zip code:</td>\n");
      out.write("                            <td><input type=\"text\" class=\"in_txt\" id=\"zip-code\" name=\"zip_code\" onkeyup=\"checkZipCodeWhileTyping()\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/red_x.gif\" alt=\"Error!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"zip-code-good\"></img>\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/green_check.png\" alt=\"Success!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"zip-code-bad\"></img>\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>State:</td>\n");
      out.write("                            <td><input type=\"text\" class=\"in_txt\" id=\"state\" name=\"state\" onkeyup=\"checkStateWhileTyping()\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/red_x.gif\" alt=\"Error!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"state-good\"></img>\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../images/green_check.png\" alt=\"Success!\" style=\"width: 20px; height: 20px;\" class=\"hidden\" id=\"state-bad\"></img>\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>Shipping speed:</td>\n");
      out.write("                            <td>\n");
      out.write("                                <input type=\"radio\" name=\"ship\" value=\"one-day\"> Burn my mouth tomorrow<br>\n");
      out.write("                                <input type=\"radio\" name=\"ship\" value=\"two-day\"> Burn my mouth two days from now<br>\n");
      out.write("                                <input type=\"radio\" name=\"ship\" value=\"other\" checked=\"checked\"> Burn my mouth whenever it gets here\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("                <br>\n");
      out.write("                <div id='submit-btn-div'>\n");
      out.write("                    <input type='submit' value='Purchase' id='submit-btn'>\n");
      out.write("                    <hr>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <script src=\"../scripts/jquery_2.2.3.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\">\n");
      out.write("            function updateQuantity(self, pepperId) {\n");
      out.write("                var quantity = self.value;\n");
      out.write("                $.ajax({\n");
      out.write("                   type: 'POST',\n");
      out.write("                   url: '/updateshoppingcart',\n");
      out.write("                   data: {\n");
      out.write("                       updateType: 'quantity',\n");
      out.write("                       quantity: quantity,\n");
      out.write("                       pepperId: pepperId\n");
      out.write("                   },\n");
      out.write("                   success: function(result) {\n");
      out.write("                       if(result.Success) {\n");
      out.write("                           var total = result.Total;\n");
      out.write("                           var subtotal = result.Subtotal;\n");
      out.write("                           $('#subtotal_' + pepperId).html(subtotal);\n");
      out.write("                           $('#total').html(total);\n");
      out.write("                       }\n");
      out.write("                   },\n");
      out.write("                   failure: function(){ }\n");
      out.write("                });\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            function removeItem(self, pepperId) {\n");
      out.write("                $.ajax({\n");
      out.write("                   type: 'POST',\n");
      out.write("                   url: '/updateshoppingcart',\n");
      out.write("                   data: {\n");
      out.write("                       updateType: 'remove',\n");
      out.write("                       pepperId: pepperId\n");
      out.write("                   },\n");
      out.write("                   success: function(result) {\n");
      out.write("                       if(result.Success) {\n");
      out.write("                           var total = result.Total;\n");
      out.write("                           self.parentElement.parentElement.remove();\n");
      out.write("                           $('#total').html(total);\n");
      out.write("                       }\n");
      out.write("                   },\n");
      out.write("                   failure: function(){ }\n");
      out.write("                });\n");
      out.write("            }\n");
      out.write("        </script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
